apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "platformSecrets.fullname" . }}
  labels: {{ include "platformSecrets.labels.standard" . | nindent 4 }}
    service: platform-secrets
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: {{ include "platformSecrets.name" . }}
      release: {{ .Release.Name }}
      service: platform-secrets
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: {{ include "platformSecrets.name" . }}
        release: {{ .Release.Name }}
        service: platform-secrets
      {{- if .Values.secrets }}
      annotations:
        checksum/secret: {{ include (print $.Template.BasePath "/secrets.yaml") . | sha256sum }}
      {{- end }}
    spec:
      serviceAccountName: {{ include "platformSecrets.fullname" . }}
      containers:
      - name: platform-secrets
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        imagePullPolicy: Always
        livenessProbe:
          httpGet:
            path: /ping
            port: tcp-web
          initialDelaySeconds: 10
          periodSeconds: 5
        readinessProbe:
          httpGet:
            path: /ping
            port: tcp-web
          initialDelaySeconds: 10
          periodSeconds: 10
        ports:
          - containerPort: 8080
            name: tcp-web
            protocol: TCP
        {{- if .Values.resources }}
        resources: {{ toYaml .Values.resources | nindent 10 }}
        {{- end }}
        env:
        - name: NP_SECRETS_PLATFORM_AUTH_URL
          value: {{ .Values.platform.authUrl | quote }}
        - name: NP_SECRETS_PLATFORM_AUTH_TOKEN
{{- if .Values.platform.token }}
{{ toYaml .Values.platform.token | indent 10 }}
{{- end }}
        - name: NP_SECRETS_K8S_API_URL
          value: https://kubernetes.default:443
        - name: NP_SECRETS_K8S_AUTH_TYPE
          value: token
        - name: NP_SECRETS_K8S_CA_PATH
          value: {{ include "platformSecrets.kubeAuthMountRoot" . }}/ca.crt
        - name: NP_SECRETS_K8S_TOKEN_PATH
          value: {{ include "platformSecrets.kubeAuthMountRoot" . }}/token
        - name: NP_SECRETS_K8S_NS
          value: {{ .Values.secretsNamespace }}
        - name: NP_CLUSTER_NAME
          value: {{ .Values.platform.clusterName }}
        {{- if .Values.sentry }}
        - name: SENTRY_DSN
          value: {{ .Values.sentry.dsn }}
        - name: SENTRY_CLUSTER_NAME
          value: {{ .Values.sentry.clusterName }}
        - name: SENTRY_APP_NAME
          value: {{ .Values.sentry.appName }}
        - name: SENTRY_SAMPLE_RATE
          value: {{ .Values.sentry.sampleRate | default 0 | quote }}
        {{- end }}
        volumeMounts:
        - mountPath: {{ include "platformSecrets.kubeAuthMountRoot" . }}
          name: kube-api-data
          readOnly: true
      {{- if .Values.imagePullSecrets }}
      imagePullSecrets: {{ toYaml .Values.imagePullSecrets | nindent 6 }}
      {{- end }}
      {{- if .Values.priorityClassName }}
      priorityClassName: {{ .Values.priorityClassName }}
      {{- end }}
      volumes:
      - name: kube-api-data
        projected:
          sources:
          - serviceAccountToken:
              expirationSeconds: 3600
              path: token
          - configMap:
              name: kube-root-ca.crt
              items:
              - key: ca.crt
                path: ca.crt
