{{- if .Values.ingress.enabled }}
{{- if .Capabilities.APIVersions.Has "networking.k8s.io/v1" }}
apiVersion: networking.k8s.io/v1
{{ else }}
apiVersion: networking.k8s.io/v1beta1
{{ end -}}
kind: Ingress
metadata:
  name: {{ include "platformSecrets.fullname" . }}
  labels: {{ include "platformSecrets.labels.standard" . | nindent 4 }}
    service: platform-secrets
  annotations:
    kubernetes.io/ingress.class: traefik
    traefik.frontend.rule.type: PathPrefix
{{- if .Values.ingress.extraAnnotations }}
{{ toYaml .Values.ingress.extraAnnotations | indent 4 }}
{{- end }}
spec:
  rules:
  {{- range .Values.ingress.hosts }}
  - host: {{ . | quote }}
    http:
      paths:
      - path: /api/v1/secrets
        backend:
          serviceName: {{ include "platformSecrets.fullname" $ }}
          servicePort: http
  {{- end }}
{{- end }}
