{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: {{ include "platformSecrets.fullname" . }}
  labels: {{ include "platformSecrets.labels.standard" . | nindent 4 }}
    service: platform-secrets
{{- with .Values.ingress.annotations }}
  annotations: {{ toYaml . | nindent 4 }}
{{- end }}
spec:
  rules:
  {{- range .Values.ingress.hosts }}
  - host: {{ . | quote }}
    http:
      paths:
      - path: /api/v1/secrets
        backend:
          serviceName: {{ include "platformSecrets.fullname" $ }}
          servicePort: http
  {{- end }}
{{- end }}
