apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "platformSecrets.fullname" . }}
  labels: {{ include "platformSecrets.labels.standard" . | nindent 4 }}

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "platformSecrets.fullname" . }}
  labels: {{ include "platformSecrets.labels.standard" . | nindent 4 }}
rules:
  # allow namespace creation
  - apiGroups: [""]
    resources: ["namespaces"]
    verbs: ["get", "list", "watch", "create"]

  # allow creation of a network policies
  - apiGroups: ["networking.k8s.io"]
    resources: ["networkpolicies"]
    verbs: ["get", "list", "create", "patch", "update"]

  # allow all kinds of a secret manipulations
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["*"]

  - apiGroups: ["discovery.k8s.io"]
    resources: ["endpointslices"]
    verbs: ["get", "list", "watch"]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "platformSecrets.fullname" . }}
  labels: {{ include "platformSecrets.labels.standard" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ include "platformSecrets.fullname" . }}
    namespace: platform
roleRef:
  kind: ClusterRole
  name: {{ include "platformSecrets.fullname" . }}
  apiGroup: rbac.authorization.k8s.io
