apiVersion: v1
kind: Service
metadata:
  name: {{ include "platformSecrets.fullname" . }}
  labels: {{ include "platformSecrets.labels.standard" . | nindent 4 }}
    service: platform-secrets
{{- with .Values.service.annotations }}
  annotations: {{ toYaml . | nindent 4 }}
{{- end }}
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 8080
    targetPort: tcp-web
  selector:
    app: {{ include "platformSecrets.name" . }}
    release: {{ .Release.Name }}
    service: platform-secrets
