repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: 'v6.0.0'
  hooks:
  - id: check-added-large-files
  - id: check-merge-conflict
    exclude: "rst$"
  - id: check-case-conflict
  - id: check-json
  - id: check-toml
  - id: check-xml
  - id: debug-statements
  - id: check-added-large-files
  - id: end-of-file-fixer
  - id: trailing-whitespace
  - id: check-symlinks
  - id: debug-statements
    exclude: ^charts/
    types_or:
    - python
    - markdown
    - rst
  # Another entry is required to apply file-contents-sorter to another file
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: 'v6.0.0'
  hooks:
  - id: file-contents-sorter
    files: |
      docs/spelling_wordlist.txt|
      .gitignore
- repo: https://github.com/sondrelg/pep585-upgrade
  rev: v1.0
  hooks:
  - id: upgrade-type-hints
    args:
    - --futures=true
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.12.11
  hooks:
  - id: ruff-check
    args: [--fix, --exit-non-zero-on-fix]
  - id: ruff-format
- repo: https://github.com/sirosen/check-jsonschema
  rev: 0.33.3
  hooks:
  - id: check-github-actions
  - id: check-github-workflows
- repo: https://github.com/python-poetry/poetry
  rev: '2.1.3'
  hooks:
  - id: poetry-install
ci:
  skip:
#  - actionlint-docker
  - check-github-actions
  - check-github-workflows
