IMAGE: neuro-docker-local-public.jfrog.io/platformsecrets:IMAGE_TAG
NP_SECRETS_REQUESTS_CPU: "0.1"
NP_SECRETS_LIMITS_CPU: "0.3"
NP_SECRETS_REQUESTS_MEMORY: "50Mi"
NP_SECRETS_LIMITS_MEMORY: "100Mi"
NP_SECRETS_REPLICAS: "2"
NP_SECRETS_PLATFORM_AUTH_URL: http://platformauthapi:8080
NP_SECRETS_K8S_NS: default
DOCKER_LOGIN_ARTIFACTORY_SECRET_NAME: "artifactory-regcred"
NP_CLUSTER_NAME: ""
