NP_SECRETS_PLATFORM_AUTH_URL: http://platformauthapi:8080
NP_SECRETS_K8S_NS: platform-jobs
NP_CLUSTER_NAME: default
NP_CORS_ORIGINS: http://localhost:8000,https://master--neuro-web.netlify.app,https://master--mts-web.netlify.app,https://master--megafon-web.netlify.app,https://master--minzdrav-web.netlify.app

platform:
  token:
    valueFrom:
      secretKeyRef:
        name: platformservices-secret
        key: compute_token

ingress:
  enabled: true

  extraAnnotations:
    external-dns.platform.neuromation.io: "true"
  hosts: [dev.neu.ro]

sentry:
  dsn: https://11316dd021994d7085c50e86c2ae404c@o454648.ingest.sentry.io/5597106
  clusterName: dev
  sampleRate: 0.1
