NP_SECRETS_PLATFORM_AUTH_URL: http://platformauthapi:8080
NP_SECRETS_K8S_NS: default
NP_CLUSTER_NAME: ""

image:
  repository: "$IMAGE_REPO"
  tag: "$IMAGE_TAG"

imagePullSecrets: []

replicas: 2

resources:
  requests:
    cpu: "0.1"
    memory: "50Mi"
  limits:
    cpu: "0.3"
    memory: "100Mi"

platform:
  token: {}

ingress:
  enabled: false

secrets: []
