IMAGE: neuro-docker-local-public.jfrog.io/platformsecrets:IMAGE_TAG
NP_SECRETS_REPLICAS: "2"
NP_SECRETS_PLATFORM_AUTH_URL: http://platformauthapi:8080
NP_SECRETS_K8S_NS: default
DOCKER_LOGIN_ARTIFACTORY_SECRET_NAME: "artifactory-regcred"
NP_CLUSTER_NAME: ""

resources:
  requests:
    cpu: "0.1"
    memory: "50Mi"
  limits:
    cpu: "0.3"
    memory: "100Mi"

platform:
  token:

ingress:
  extraAnnotations: {}
  hosts: []

secrets: []
