name: Release

on:
  workflow_run:
    workflows:
      - CI
    types:
      - completed

permissions:
  contents: read
  packages: write

jobs:
  publish_image:
    name: Publish Image
    runs-on: ubuntu-latest
    concurrency: release_image
    outputs:
      tag: steps.release.outputs.tag
      version: steps.release.outputs.version
      skip: steps.release.outputs.skip
    steps:
    - name: Purge old artifacts
      uses: kolpav/purge-artifacts-action@v1
      with:
        token: ${{ secrets.GH_TOKEN }}
        expire-in: 30mins
    - name: Release image
      id: release
      uses: neuro-inc/release-image-action@v21.9.36
      with:
        image: platformsecrets
        token: ${{ secrets.GH_TOKEN }}
    - name: Checkout commit
      uses: actions/checkout@v2
      with:
        ref: ${{ github.event.workflow_run.head_sha }}
        fetch-depth: 0
    - name: Github Release
      if: ${{ ! steps.release.outputs.skip }}
      run: |
        if [[ -n $PRERELEASE ]]; then
          gh release create "$TAG" --prerelease --notes "docker pull ghcr.io/neuro-inc/platformsecrets:$VERSION"
        else
          gh release create "$TAG" --notes "docker pull ghcr.io/neuro-inc/platformsecrets:$VERSION"
        fi
      shell: bash
      env:
        TAG: ${{ steps.release.outputs.tag }}
        VERSION: ${{ steps.release.outputs.version }}
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
        PRERELEASE: ${{ steps.release.outputs.prerelease }}
  publish_chart:
    name: Release Helm chart
    runs-on: ubuntu-latest
    needs: publish_image
    concurrency: release_helm_chart
    steps:
    - name: Checkout commit
      uses: actions/checkout@v2
      with:
        ref: ${{ github.event.workflow_run.head_sha }}
        fetch-depth: 0
    - name: Install Helm
      uses: azure/setup-helm@v1
      with:
        version: v3.7.0
    - name: Create chart
      run: make helm_create_chart
      env:
        TAG: ${{ needs.publish_image.outputs.tag }}
        GITHUB_OWNER: ${{ github.repository_owner }}
        HELM_CHART_VERSION: ${{ needs.publish_image.outputs.version }}
        HELM_APP_VERSION: ${{ needs.publish_image.outputs.version }}
    - name: Release chart
      if: ${{ ! needs.publish_image.outputs.skip }}
      uses: helm/chart-releaser-action@v1.2.1
      with:
        charts_dir: temp_charts
      env:
        CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
