name: Release Helm chart

on:
  workflow_run:
    workflows:
    - Release Image
    types:
    - completed

permissions:
  contents: read
  packages: write

jobs:
  publish:
    name: Release Helm chart
    runs-on: ubuntu-latest
    concurrency: release_helm_chart
    # if: startsWith(github.ref, 'refs/tags/v')
    steps:
    - name: Checkout commit
      uses: actions/checkout@v2
      with:
        ref: ${{ github.event.workflow_run.head_sha }}
        fetch-depth: 0
    - name: Set tag
      run: |
        REF="${{ github.event.workflow_run.head_branch }}"
        echo "TAG=${REF#refs/tags/v}" >> $GITHUB_ENV
    - name: Install Helm
      uses: azure/setup-helm@v1
      with:
        version: v3.7.0
    - name: Create chart
      run: make helm_create_chart
      env:
        GITHUB_OWNER: ${{ github.repository_owner }}
        HELM_CHART_VERSION: ${{ env.TAG }}
        HELM_APP_VERSION: ${{ env.TAG }}
    - name: Release chart
      uses: helm/chart-releaser-action@v1.2.1
      with:
        charts_dir: temp_charts
      env:
        CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
